spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/donation-server #;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none #스테이징과 운영 서버는 validate 또는 none
    properties:
      hiberate:
#        show-sql: true
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info
