spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test #;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hiberate:
        show-sql: true
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
